---
clusterName: kochhaus
talosVersion: v1.3.3
kubernetesVersion: v1.26.3
endpoint: https://192.168.20.200:6443
allowSchedulingOnMasters: true
cniConfig:
  name: custom
  urls:
    - https://docs.projectcalico.org/archive/v3.24/manifests/tigera-operator.yaml
    - https://github.com/haraldkoch/kochhaus-talos/raw/main/infrastructure/talos/manifests/tigera.yaml
additionalApiServerCertSans:
  - 192.168.20.203
  - 192.168.20.1
additionalMachineCertSans:
  - 192.168.20.203
  - 192.168.20.1
clusterPodNets:
  - 10.106.0.0/20
clusterSvcNets:
  - 10.106.16.0/24
nodes:
  - hostname: talos1
    ipAddress: 192.168.20.200
    controlPlane: true
    installDisk: /dev/vda
    disableSearchDomain: true
    nameservers:
      - 192.168.20.1
    networkInterfaces:
      - interface: eth0
        dhcp: true
        vip:
          ip: 192.168.20.203
        mtu: 1500
  - hostname: talos2
    ipAddress: 192.168.20.201
    controlPlane: true
    installDisk: /dev/vda
    disableSearchDomain: true
    nameservers:
      - 192.168.20.1
    networkInterfaces:
      - interface: eth0
        dhcp: true
        vip:
          ip: 192.168.20.203
        mtu: 1500
  - hostname: talos3
    ipAddress: 192.168.20.202
    controlPlane: true
    installDisk: /dev/vda
    disableSearchDomain: true
    nameservers:
      - 192.168.20.1
    networkInterfaces:
      - interface: eth0
        dhcp: true
        vip:
          ip: 192.168.20.203
        mtu: 1500
controlPlane:
  patches:
    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl
  # inlinePatch:
  #  machine:
  #    registries:
  #      mirrors:
  #        docker.io:
  #          endpoints:
  #            - https://harbor.${domainName}/v2/docker.io
  #        k8s.gcr.io:
  #          endpoints:
  #            - https://harbor.${domainName}/v2/k8s.gcr.io
  #        quay.io:
  #          endpoints:
  #            - https://harbor.${domainName}/v2/quay.io
  #        gcr.io:
  #          endpoints:
  #            - https://harbor.${domainName}/v2/gcr.io
  #        ghcr.io:
  #          endpoints:
  #            - harbor.${domainName}/ghcr.io
  #        public.ecr.aws:
  #          endpoints:
  #            - https://harbor.${domainName}/v2/public.ecr.aws
  #        registry.k8s.io:
  #          endpoints:
  #            - https://harbor.${domainName}/v2/registry.k8s.io
